services:
  mongodb_compcommondb:
    image: mongo
    container_name: mongodb_compcommondb
    ports:
      - "27029:27017"
    volumes:
      - mongodb-compcommondb-data:/data/db
    restart: unless-stopped

  mongodb_aitrcommondb:
    image: mongo
    container_name: mongodb_aitrcommondb
    ports:
      - "27028:27017"
    volumes:
      - mongodb-aitrcommondb-data:/data/db
    restart: unless-stopped

  mongodb_simcommondb:
    image: mongo
    container_name: mongodb_simcommondb
    ports:
      - "27030:27017"
    volumes:
      - mongodb-simcommondb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-compcommondb-data:
  mongodb-aitrcommondb-data:
  mongodb-simcommondb-data:
